---
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"
  - "nightly"

os:
  - linux

sudo: false

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install ansible
  - ansible --version
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - ansible-playbook tests/test.yml -i tests/inventory.yml -v --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/