---
os:
  - linux

sudo: required

services:
  - docker

env:
  global:
    - ROLE_NAME: "ansible-role-powershell"
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: ubuntu1804

install:
  - pip install molecule docker

before_script:
  - cd ../

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/