---
- name: Install PowerShell
  block:

  - name: Search for Latest Artifact
    block:

    - name: Get Latest PowerShell Release
      uri:
        url: https://api.github.com/repos/powershell/powershell/releases/latest
        return_content: true
      register: latest_release
      delegate_to: localhost

    - name: Build Regex Query
      set_fact:
        powershell_artifact_search: "({{ powershell_windows_artifact_id + '-' + powershell_windows_artifact_arch + powershell_windows_artifact_ext }})+$"

    - name: Debug - Print Regex Query
      debug:
        msg: "Query for {{ powershell_artifact_search }}"

    - name: Search for the Artifact
      set_fact:
        powershell_artifact_url: "{{ item.browser_download_url }}"
      loop: "{{ latest_release.json.assets }}"
      when: item.name is regex(powershell_artifact_search)

    when: powershell_version == 'latest'

  - name: Search for Specific Artifact
    block:

    - name: Query for List of PowerShell Releases
      uri:
        url: https://api.github.com/repos/powershell/powershell/releases
        return_content: true
      register: releases
      delegate_to: localhost

    - name: Build Regex Query
      set_fact:
        powershell_artifact_search: "({{ powershell_artifact_windows_id + '-' + powershell_artifact_windows_arch + powershell_artifact_windows_ext }})+$"

    - name: Debug - Print Regex Query
      debug:
        msg: "Query for {{ powershell_artifact_search }}"

    - name: Search for the Artifact
      set_fact:
        powershell_artifact_url: "{{ item.browser_download_url }}"
      loop: "{{ latest_release.json.assets }}"
      when: item.name is regex(powershell_artifact_search)

    when: powershell_version != 'latest'

  - name: Debug - Print Download URL
    debug:
      msg: "Downloading {{ powershell_artifact_url }}"

  - name: Download PowerShell Artifact
    win_get_url:
      url: "{{ powershell_artifact_url }}"
      dest: C:\Windows\Temp\ps.msi

  - name: Install PowerShell Artifact
    win_package:
      state: present
      product_id: pscore
      arguments:
        - "ADD_EXPLORER_CONTEXT_MENU_OPENPOWERSHELL={{ (powershell_windows_enable_context_menu == true) | ternary('1','0') }}"
        - "ENABLE_PSREMOTING={{ (powershell_windows_enable_psremoting == true) | ternary('1','0') }}"
        - "REGISTER_MANIFEST={{ (powershell_windows_enable_register_manifest == true) | ternary('1','0') }}"
      path: C:\Windows\Temp\ps.msi

  - name: Post Installation Tasks
    include_tasks: install-post.yml

  when: powershell_state == 'present'

- name: Remove PowerShell
  win_package:
    state: absent
    product_id: pscore
  when: powershell_state == 'absent'