---
- name: Debian | Ensure PowerShell is Present
  block:
    - name: Ubuntu - Download & Install GPG Key
      apt:
        deb: "https://packages.microsoft.com/config/ubuntu/\
          {{ ansible_distribution_major_version }}.04/packages-microsoft-prod.deb"
        state: present

    - name: Debian - Download & Install PowerShell
      apt:
        name: >-
          {{ (powershell_version == 'latest') |
             ternary(powershell_debian_package_name,
             (powershell_debian_package_name + '=' + powershell_version)) }}
        autoclean: true
        state: present
        update_cache: true

    - name: Debian - Install Modules
      shell: >
        if(-not (Get-Module -ListAvailable -Name {{ item }})) {
          Install-Module -Name {{ item }} -Scope {{ powershell_redhat_modules_scope }} -Force
        }
      args:
        executable: /usr/bin/pwsh
      loop: "{{ powershell_modules }}"
  when: powershell_state == 'present'

- name: Debian | Ensure PowerShell is Absent
  block:
    - name: Debian - Download & Install GPG Key
      apt:
        deb: "https://packages.microsoft.com/config/ubuntu/\
          {{ ansible_distribution_major_version }}.04/packages-microsoft-prod.deb"
        state: absent
      when: ansible_distribution == "Ubuntu"

    - name: Debian - Download & Install PowerShell
      apt:
        name: "{{ powershell_debian_package_name }}"
        autoclean: true
        state: absent
        update_cache: true
  when: powershell_state == 'absent'

