---
- name: Ubuntu
  block:

  - name: Install PowerShell
    block:
    - name: Ubuntu - Download & Install GPG Key
      apt:
        deb: https://packages.microsoft.com/config/ubuntu/{{ ansible_distribution_major_version }}.04/packages-microsoft-prod.deb
        state: present 

    - name: Ubuntu - Download & Install PowerShell
      apt:
        name: "{{ (powershell_version == 'latest') | ternary(powershell_debian_package_name, (powershell_debian_package_name + '=' + powershell_version)) }}"
        autoclean: true
        state: present
        update_cache: true

    - name: Post Installation Tasks
      include_tasks: install-post.yml

    when: powershell_state == 'present'

  - name: Remove PowerShell
    block:
    - name: Ubuntu - Download & Install GPG Key
      apt:
        deb: https://packages.microsoft.com/config/ubuntu/{{ ansible_distribution_major_version }}.04/packages-microsoft-prod.deb
        state: absent 
      when: ansible_distribution == "Ubuntu"

    - name: Ubuntu - Download & Install PowerShell
      apt:
        name: "{{ powershell_debian_package_name }}"
        autoclean: true
        state: absent
        update_cache: true
    when: powershell_state == 'absent'

  become: true
  when: ansible_distribution == 'Ubuntu'