---
- block:
  - name: Add Microsoft Repository
    get_url:
      dest: /etc/yum.repos.d/microsoft.repo
      url: https://packages.microsoft.com/config/rhel/7/prod.repo

  - name: Install PowerShell
    yum:
      update_cache: true
      name: "{{ powershell_redhat_package_name }}"
      state: present

  - name: Post Installation Tasks
    include_tasks: install-post.yml
  become: true
  when: powershell_state == 'present'

- block:
  - name: Remove Microsoft Repository
    file:
      path: /etc/yum.repos.d/microsoft.repo
      state: absent

  - name: Remove PowerShell
    yum:
      update_cache: true
      name: "{{ powershell_redhat_package_name }}"
      state: absent
  become: true
  when: powershell_state == 'absent'