---
dependency:
  name: galaxy
driver:
  name: delegated
  hostname: 10.1.1.1
  username: jz@vcenter.internal.zollo.lab
  password: password
  validate_certs: false
  datacenter: "DC1"
  folder: "/Path/To/VM"
  vm_username: "guestOSun"
  vm_password: password for guest os
  connection: winrm
  port: 5986
  winrm_transport: ntlm
  winrm_server_cert_validation: ignore
lint:
  name: yamllint
platforms:
  - name: instance
    template: ci-win2016
    snapshot_src: baseline
    memory_mb: 4096
    cpus: 2
    network: VN-NSX-V10
    datastore: vSAN
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  log: true
verifier:
  name: testinfra
  lint:
    name: flake8