---
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: ar-python-default-centos7
    image: geerlingguy/docker-centos7-ansible:latest
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    pre_build_image: true
  - name: ar-python-default-centos8
    image: geerlingguy/docker-centos8-ansible:latest
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    pre_build_image: true
  - name: ar-powershell-ubuntu1804
    image: geerlingguy/docker-ubuntu1804-ansible:latest
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    pre_build_image: true
  - name: ar-powershell-ubuntu2004
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    pre_build_image: true
provisioner:
  name: ansible
  env:
    JUNIT_OUTPUT_DIR: ${PWD}
    PYTHONWARNINGS: "ignore:Unverified HTTPS request"
  log: true
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer,junit
